// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMglBcw1azDHjdVGH3dFLXYUGOtVXtIRg',
    appId: '1:922327759741:web:385305bf8023a9295daa14',
    messagingSenderId: '922327759741',
    projectId: 'jemberwisataapp',
    authDomain: 'jemberwisataapp.firebaseapp.com',
    storageBucket: 'jemberwisataapp.appspot.com',
    measurementId: 'G-6MJGZB1CKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQoL5nyDYzbUU21VBLoZ9EFEvyzArXx6k',
    appId: '1:922327759741:android:bb418cbb56e83ad65daa14',
    messagingSenderId: '922327759741',
    projectId: 'jemberwisataapp',
    storageBucket: 'jemberwisataapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM3hTSOzU4C6-5BINYPj_K50AiCrUzZ5U',
    appId: '1:922327759741:ios:da2559f2781d7fcf5daa14',
    messagingSenderId: '922327759741',
    projectId: 'jemberwisataapp',
    storageBucket: 'jemberwisataapp.appspot.com',
    iosBundleId: 'com.example.jemberWisata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMglBcw1azDHjdVGH3dFLXYUGOtVXtIRg',
    appId: '1:922327759741:web:e1283c28865fb4925daa14',
    messagingSenderId: '922327759741',
    projectId: 'jemberwisataapp',
    authDomain: 'jemberwisataapp.firebaseapp.com',
    storageBucket: 'jemberwisataapp.appspot.com',
    measurementId: 'G-7TZH5LW7FD',
  );
}
